---

- name: "configure : repository"
  apt_repository:
    repo: "deb http://ftp.de.debian.org/debian testing main"
  register: repo

- name: "configure : Default-Release"
  lineinfile:
    path: /etc/apt/apt.conf.d/00local
    line: 'APT::Default-Release "stable";'
    regexp: ".*Default-Release.*"
    create: yes

- name: "install : python{{ python_version }}"
  apt:
    update_cache: "{% if repo is changed %}yes{% else %}no{% endif %}"
    name:
      - "python{{ python_version }}"
      - python3-distutils
    default_release: testing
    state: "{{ python_apt_state }}"
