---

- name: "install : python{{ python_version }}"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - "python{{ python_version }}"
      - "python{{ python_version }}-distutils"
    state: "{{ python_apt_state }}"
