---

- name: "install : python{{ python_version }}"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - "python{{ python_version }}"
      - "python{{ python_version }}-distutils"
    state: "{{ python_apt_state }}"

- name: "check : python version"
  shell: "python{{ python_version }} -V"
  register: cmd
  failed_when: "python_version not in cmd.stdout"
  changed_when: false
